-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE matches (
    id SERIAL PRIMARY KEY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    winner text NOT NULL,
    loser text NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX matches_pkey ON matches(id int4_ops);
